evaluator = dict(
    type='ImageidEvaluator',
    metrics=dict(
        aesthetic=dict(
            type='AestheticScore',
            batch_size=1,
        ),
        imaging_quality=dict(
            type='ImagingQuality',
            batch_size=1,
        ),
        facesim=dict(
            type='FaceSim',
        ),
        antifacesim=dict(
            type='AntiFaceSim',
        ),
        landmarkdiff=dict(
            type='LandmarkDiff',
        ),
        clipi=dict(
            type='ClipI',
        ),
        clipt=dict(
            type='ClipT',
            truncate=True
        ),
        posediv=dict(
            type='PoseDiv',
        ),
        exprdiv=dict(
            type='ExprDiv',
        ),
    ),
    visual=dict(
        visualposediv=dict(
            type='VisualPoseDiv',
            size=100
        )
    )
)
